modLoader="javafml" #mandatory
loaderVersion="[41,)" #mandatory
issueTrackerURL="https://github.com/oitsjustjose/Natural-Progression/issues"
license="GNU GPLv3"

[[mods]]
modId="natprog"
version="${file.jarVersion}"
displayName="Natural Progression"
displayURL=""
credits="Contributors on GitHub"
authors="oitsjustjose"
description='''
A configurable mod that adds difficulty to the early game by forcing pebble collection, 
knapping, and preventing wood breaking with a bare hand.

Support me on Patreon at https://patreon.com/oitsjustjose
'''
[[dependencies.natprog]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[41,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.natprog]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.natprog]]
    modId="quark"
    mandatory=false
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.natprog]]
    modId="create"
    mandatory=false
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
